"""initial schema - scan_history, website_scans, scan_progress

Revision ID: 0b01a5205403
Revises: 
Create Date: 2026-02-10 23:46:43.898877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b01a5205403'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('email_breached', sa.Boolean(), nullable=False),
    sa.Column('phishing_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.Column('pwned_count', sa.Integer(), nullable=True),
    sa.Column('breach_details', sa.Text(), nullable=True),
    sa.Column('breach_source', sa.String(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_history_id'), 'scan_history', ['id'], unique=False)
    op.create_table('scan_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('current_step', sa.String(), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('step_details', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.Column('estimated_seconds_remaining', sa.Integer(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('has_error', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_progress_id'), 'scan_progress', ['id'], unique=False)
    op.create_index(op.f('ix_scan_progress_scan_id'), 'scan_progress', ['scan_id'], unique=True)
    op.create_table('website_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('client_ip', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('overall_grade', sa.String(), nullable=False),
    sa.Column('http_scan_json', sa.Text(), nullable=True),
    sa.Column('ssl_scan_json', sa.Text(), nullable=True),
    sa.Column('dns_scan_json', sa.Text(), nullable=True),
    sa.Column('tech_scan_json', sa.Text(), nullable=True),
    sa.Column('owasp_assessment_json', sa.Text(), nullable=True),
    sa.Column('scan_duration_ms', sa.Integer(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.Column('permission_confirmed', sa.Boolean(), nullable=True),
    sa.Column('owner_confirmed', sa.Boolean(), nullable=True),
    sa.Column('legal_accepted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_scans_id'), 'website_scans', ['id'], unique=False)
    op.create_index(op.f('ix_website_scans_url'), 'website_scans', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_website_scans_url'), table_name='website_scans')
    op.drop_index(op.f('ix_website_scans_id'), table_name='website_scans')
    op.drop_table('website_scans')
    op.drop_index(op.f('ix_scan_progress_scan_id'), table_name='scan_progress')
    op.drop_index(op.f('ix_scan_progress_id'), table_name='scan_progress')
    op.drop_table('scan_progress')
    op.drop_index(op.f('ix_scan_history_id'), table_name='scan_history')
    op.drop_table('scan_history')
    # ### end Alembic commands ###
